---
# tasks file for ansible-role-win-debloat
- name: Debug Whitelist Apps
  ansible.builtin.debug:
    msg: "{{ win_appxdebloat_regex_whitelist_apps | join('|') }}"
  when:
    - win_appxdebloat_show_debug

- name: Remove Appx
  ansible.windows.win_shell: |
    [regex]$WhitelistedApps = "{{ win_appxdebloat_regex_whitelist_apps | join('|') }}"
    Get-AppxPackage -AllUsers | Where-Object {($_.Name -NotMatch $WhitelistedApps) -and ($_.NonRemovable -eq $false) -and ($_.IsFramework -eq $false)} | Remove-AppxPackage -AllUsers
  register: win_appxdebloat_remove_appx_result
  ignore_errors: true

- name: Debug win_appxdebloat_remove_appx_result
  ansible.builtin.debug:
    var: win_appxdebloat_remove_appx_result
  when:
    - win_appxdebloat_show_debug

- name: Remove Appx 2nd
  ansible.windows.win_shell: |
    [regex]$WhitelistedApps = "{{ win_appxdebloat_regex_whitelist_apps | join('|') }}"
    Get-AppxPackage -AllUsers | Where-Object {($_.Name -NotMatch $WhitelistedApps) -and ($_.NonRemovable -eq $false) -and ($_.IsFramework -eq $false)} | Remove-AppxPackage -AllUsers
  register: win_appxdebloat_remove_appx2_result
  ignore_errors: true

- name: Debug win_appxdebloat_remove_appx2_result
  ansible.builtin.debug:
    var: win_appxdebloat_remove_appx2_result
  when:
    - win_appxdebloat_show_debug

- name: Remove AppxProvisionedPackage
  ansible.windows.win_shell: |
    [regex]$WhitelistedApps = "{{ win_appxdebloat_regex_whitelist_apps | join('|') }}"
    $AppxRemoval = Get-AppxProvisionedPackage -Online | Where-Object {$_.PackageName -NotMatch $WhitelistedApps} 
    ForEach ( $App in $AppxRemoval) {
      Remove-AppxProvisionedPackage -Online -PackageName "$App.PackageName"
    }
  register: win_appxdebloat_remove_appxprovisioned_result
  ignore_errors: true

- name: Debug win_appxdebloat_remove_appxprovisioned_result
  ansible.builtin.debug:
    var: win_appxdebloat_remove_appxprovisioned_result
  when:
    - win_appxdebloat_show_debug

- name: Remove AppxProvisionedPackage 2nd
  ansible.windows.win_shell: |
    [regex]$WhitelistedApps = "{{ win_appxdebloat_regex_whitelist_apps | join('|') }}"
    Get-AppxProvisionedPackage -Online | Where-Object {$_.PackageName -NotMatch $WhitelistedApps} | Remove-AppxProvisionedPackage -Online
    
  register: win_appxdebloat_remove_appxprovisioned2_result
  ignore_errors: true

- name: Debug win_appxdebloat_remove_appxprovisioned2_result
  ansible.builtin.debug:
    var: win_appxdebloat_remove_appxprovisioned2_result
  when:
    - win_appxdebloat_show_debug

- name: Reboot
  ansible.windows.win_reboot:
    post_reboot_delay: "{{ win_appxdebloat_post_reboot_delay }}"
    pre_reboot_delay: "{{ win_appxdebloat_pre_reboot_delay }}"
    reboot_timeout: "{{ win_appxdebloat_reboot_timeout }}"
  when:
    - win_appxdebloat_reboot_after

- name: Ensure WinRM is running
  ansible.windows.win_service_info:
    name: WinRM
  register: result_service_winrm_started
  until: result_service_winrm_started.services[0].state == "started"
  retries: "{{ win_appxdebloat_check_winrm_retries }}"
  delay: 15
  when:
    - win_appxdebloat_check_winrm
...
