---
# This file contains the default tasks for the ansible-role-win-debloat role,
# which is used to remove unwanted Appx packages from Windows installations.
- name: Include the loop task file for win_appxdebloat
  include_tasks: "{{ role_path }}/tasks/loop_task.yml"
  loop: "{{ range(win_appxdebloat_loop_count) | list }}"
...
